import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tignle",
    description: "Generated by create next app , and created by Ghoumidate Zakaria",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <div >
        <div
          className={``}
        >
          {children}
        </div>
      </div>
    );
  }