import { Metadata } from "next";
import { Geist } from "next/font/google";

const geist = Geist({
  subsets: ['latin'],
  display: 'swap',
  preload: true,
  fallback: ['sans-serif'],
  adjustFontFallback: true,
  variable: '--font-geist',
});
export const metadata: Metadata = {
    title: "Tignle",
    description: "Generated by create next app , and created by Ghoumidate Zakaria",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <div >
        <div
          className={` ${geist.className} bg-gradient-to-b to-[#fc7348]/20 to-[380%] from-[30%] from-transparent min-h-screen `}
        >
          {children}
        </div>
      </div>
    );
  }